[package]
name = "rpi_sim868"
version = "0.1.7"
edition = "2021"
authors = ["Jan Kowal <janokowal@outlook.com>"]
description = "RPi SIM868 is a crate designed to facilitate interaction with the Waveshare SIM868 HAT for Raspberry Pi."
documentation = "https://docs.rs/rpi_sim868"
homepage = "https://github.com/j-kowal/rpi-sim868"
license = "MIT"
readme = "README.md"
rust-version = "1.56"
categories = ["embedded"]
keywords = ["raspberry", "pi", "sim800", "waveshare", "sim868"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["hardware"]
hardware = ["rppal"]
mock = []

[dependencies]
chrono = "0.4.41"
colored = "3.1.1"
lazy_static = "1.5.0"
log = "0.4.29"
priority-queue = "2.7.0"
regex = "1.12.3"
rppal = { version = "0.22.1", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_url_params = "0.2.1"
simple_logger = "5.2.0"
tokio = { version = "1.52.1", features = ["rt-multi-thread", "sync", "time"] }
url = "2.5.8"
uuid = { version = "1.23.1", features = ["v4", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
tokio-test = "0.4"
tokio = { version = "1.52.1", features = ["rt-multi-thread", "sync", "time", "test-util", "macros"] }
rpi_sim868 = { path = ".", default-features = false, features = ["mock"] }
